# Application Configuration
app:
  name: "shadow-id"
  version: "1.0.0"
  environment: "development"

# Logging Configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"

# Database Configuration
database:
  driver: "memory"
  host: "localhost"
  port: 5432
  name: "shadow_id"
  user: "postgres"
  password: ""
  ssl_mode: "disable"
  max_connections: 10
  max_idle_connections: 5
  connection_max_lifetime: "1h"

# Server Configuration (for future HTTP API)
server:
  host: "localhost"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

# Security Configuration
security:
  jwt_secret: "your-secret-key"
  jwt_expiration: "24h"
  bcrypt_cost: 12

# Feature Flags
features:
  enable_metrics: true
  enable_tracing: false
  enable_profiling: false
