// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1, arg2) {
  return window['go']['wails']['App']['CreateUser'](arg1, arg2);
}

export function GetAppInfo() {
  return window['go']['wails']['App']['GetAppInfo']();
}

export function GetUser(arg1) {
  return window['go']['wails']['App']['GetUser'](arg1);
}

export function Greet(arg1) {
  return window['go']['wails']['App']['Greet'](arg1);
}
