// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {commands} from '../models';
import {queries} from '../models';

export function CreateUser(arg1:string,arg2:string):Promise<commands.CreateUserResult>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetUser(arg1:string):Promise<queries.GetUserResult>;

export function Greet(arg1:string):Promise<string>;
